<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form style="margin: 50px;" action="" method="post">
        <textarea rows="2" cols="100" name='content'></textarea>
        <button type="submit">Submit</button>
    </form>
    <div>
        <h1><?php if($message != '')echo $message ?></h1>
    </div>
</body>
</html>